---
title: "Testing tidygraph: map_dfs()"
author: "JM Delgado"
date: "`r Sys.Date()`"
output:
  slidy_presentation:
    duration: 5    
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(dplyr,warn.conflicts=FALSE)
library(tidygraph,warn.conflicts=FALSE)
library(ggraph,warn.conflicts=FALSE)
library(igraph)

```

With a generic graph:

```{r, results='asis'}



g=create_tree(40, children = 3, directed = TRUE,mode='out') %>%
  mutate(name=as.factor(1:40)) %>%
  mutate(rank=map_dfs_back_int(node_is_root(),.f=function(node,rank,...) {
    return(rank)  
  }))

ggraph(g) +
  geom_node_point() +
  geom_node_label(aes(label = rank)) +# repel=TRUE
  geom_edge_link0(arrow = arrow(length = unit(4, 'mm')))
```

With a reservoir graph upstream of oros:

```{r, results='asis'}

library(a5udes)

# id='44755' # oros
id='34560' # smaller network
# id='34689' # even smaller

sub=all_simple_paths(reservoir_graph,from=id,mode='in') %>%
  unlist %>%
  unique

subgraph = induced_subgraph(reservoir_graph, sub ,impl='auto')

graph.reverse <- function (graph) {
  if (!is.directed(graph))
    return(graph)
  e <- get.data.frame(graph, what="edges")
  ## swap "from" & "to"
  neworder <- 1:length(e)
  neworder[1:2] <- c(2,1)
  e <- e[neworder]
  names(e) <- names(e)[neworder]
  graph.data.frame(e, vertices = get.data.frame(graph, what="vertices"))
}

g=subgraph %>%
  graph.reverse(.) %>%
  as_tbl_graph %>% mutate(rank=map_dfs_back_int(node_is_root(),.f=function(node,rank,...) {
    return(rank)  
  }))

ggraph(g) +
  geom_node_point() +
  geom_node_label(aes(label = rank)) +# repel=TRUE
  geom_edge_link0(arrow = arrow(length = unit(4, 'mm')))
```

Route overspill:

1. define size of each node's dataframe by determining how many upstream nodes are there. Reserve memory for this.
2. loop on rank
3. on each node do a water balance and pass results downstream

```{r, results='asis'}

g %>% activate(nodes) %>% arrange(desc(rank)) %>% as_tibble


```
